### ISSUE TITLE
5GTANGO LLCM: Allow port mappings for VNFs

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-emu#295]
The SM pilot needs it to e.g. show the DT web interface or to connect to the Samba with a real machine.

Idea: Include port mapping parameter into VNFDs (CDUs) that are only used by emulator and trigger port mappings `-p xx:yyy` when the containers are started.

Field in connection points to be used `publish`.

Example: https://github.com/sonata-nfv/tng-industrial-pilot/blob/30e30a0b26682ee4f17275f2ccb82ca360af160a/sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_cc_emulator.yml#L56

In the CDU connection point do:
```yaml
connection_points:
      - id: data
        port: 9091
        publish: {9091: 9091}
```
